# Generated by Django 6.0.2 on 2026-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=255)),
                ('simphony_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload_enviado', models.JSONField()),
                ('resposta_api', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
