# Generated by Django 5.0.4 on 2026-04-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simphony_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('registros_sincronizados', models.IntegerField(default=0)),
                ('erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
